spring:
  data:
    mongodb:
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST:mongodb}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:customer}
      authentication-database: ${MONGO_AUTH_DB:admin}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

  mail:
    host: ${MAIL_HOST:mail-dev}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  port: ${SERVER_PORT:8040}

eureka:
  instance:
    hostname: notification-service