spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/order_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

server:
  port: ${SERVER_PORT:8070}

eureka:
  instance:
    hostname: order-service

application:
  config:
    customer-url: http://${GATEWAY_HOST:gateway-service}:${GATEWAY_PORT:8222}/api/v1/customers
    payment-url: http://${GATEWAY_HOST:gateway-service}:${GATEWAY_PORT:8222}/api/v1/payments
    product-url: http://${GATEWAY_HOST:gateway-service}:${GATEWAY_PORT:8222}/api/v1/products

