spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/payment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

server:
  port: ${SERVER_PORT:8060}

eureka:
  instance:
    hostname: payment-service

