spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/product
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT:8050}

eureka:
  instance:
    hostname: product-service


