CREATE DATABASE "order";
CREATE DATABASE "product";
CREATE DATABASE "payment";

GRANT ALL PRIVILEGES ON DATABASE "order" TO postgres;
GRANT ALL PRIVILEGES ON DATABASE "product" TO postgres;
GRANT ALL PRIVILEGES ON DATABASE "payment" TO postgres;