FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /build

COPY product/pom.xml .
RUN mvn dependency:go-offline

COPY product/src ./src
RUN mvn clean package -DskipTests

FROM amazoncorretto:17-alpine
ARG PROFILE=dev

WORKDIR /app
COPY --from=build /build/target/product-*.jar app.jar

EXPOSE 8050

ENTRYPOINT ["java","-jar","-Dspring.profiles.active=${PROFILE}","app.jar"]
