FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /build

COPY order/pom.xml .
RUN mvn dependency:go-offline

COPY order/src ./src
RUN mvn clean package -DskipTests

FROM amazoncorretto:17-alpine
ARG PROFILE=dev

WORKDIR /app
COPY --from=build /build/target/order-*.jar app.jar

EXPOSE 8070

ENTRYPOINT ["java","-jar","-Dspring.profiles.active=${PROFILE}","app.jar"]
